### ISSUE TITLE
Como usuario (fabricante) quiero una vista donde se renderice todo lo asociado a mi cuenta

### ISSUE THREAD

**Issue by Nestorfron** [Nestorfron/final-project-GP-IL-JL-NF#89]
- [x] Front
    - [x] Crear vista para mi cuenta
    - [x] Renderizar mis cervecerias
    - [x] Renderizar mis productos
    - [x] Renderizar mis datos
    - [x] Editar mis datos
    - [x] Editar mis productos
    - [x] Editar mis cervecerias
    - [x] Borrar mis productos
    - [x] Borrar mis cervecerias

 - [x] Back 
    - [x] Endpont para obtener mis productos
    - [x] Endpoint para obtener mis cervecerías
    - [x] endpoint para editar mi producto
    - [x] endpoint para editar mi cerveceria
    - [x] endpoint para editar mis datos
    - [x] endpoint para borrar mi producto
    - [x] endpoint para borrar mi cervecería
